version: "3"
services:
  database:
    image: "postgres"
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=realworld
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=nestjsrealworld
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data:  # named volumes can be managed easier using docker-compose
